version: "3"
services:
  docker_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MQTT_BROKER_ID=test
      - MQTT_BROKER_HOST=test.mosquitto.org
      - MQTT_BROKER_PORT=1883
      - RUST_LOG=debug
